### ISSUE TITLE
On chain factory for token contracts

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#128]
To investigate the possibility of having a single code bundle on-chain that can be constructed with different params. 

Simplest would be to have an initial account which is permitted to mint that can then be permanently revoked. Or simply a fixed supply to begin with distributed to specified account(s).

**Comment by anorth** [comment]
Everything that would be hard-coded in a token to make it special needs to be in state instead. E.g. name, code etc. And yes configurable minting policy.
