### ISSUE TITLE
Derive clone for externally exported types

### ISSUE THREAD

**Issue by ZenGround0** [helix-onchain/filecoin#131]
Because rust doesn't let us derive builtin traits on external types this would make development a bit nicer.  There's a need for message params (see [here](https://github.com/filecoin-project/builtin-actors/pull/735#discussion_r989294811)) but probably helpful for all exported types.

**Comment by alexytsu** [comment]
https://github.com/helix-onchain/filecoin/pull/132#issue-1402446294

Have derived Clone for externally available message types
