### ISSUE TITLE
Investigate use of u128 rather than BigInt as token primitive

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#27]
> Not much comments on Fungible Token Standards, do have a lot to say on Non Fungible Token Standards. But I do notice many new chains are using u128/u64 over BigInt, simply because they are primitives and more than sufficient to cover all use cases.
> 
> _Originally posted by @Tom-OriginStorage in https://github.com/filecoin-project/FIPs/discussions/407#discussioncomment-3176582_

**Comment by anorth** [comment]
I chose BigInt because that's the type baked into the chain/VM to represent the native token. Even though the FVM uses a u128 to pass it across the VM boundary. Basically I think we should follow the VM here, and I don't think they're likely to change it.
