### ISSUE TITLE
Handle resolution of non ID addresses for sends

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#31]
This exposes an interesting chicken and egg problem.

In the proposal, I wrote:
> An uninitialised pubkey address can receive tokens (because receiver hook will initialise it), but cannot be authorized as a spender

I was about to say you won't always have the actor ID so change to address, but I realise that we can't have the token state reflecting the new balances persisted if we don't know the receiving actor ID.

I think the required workaround will be that address resolution (in the actor code) needs to initialise actors if necessary. See `resolve_to_id_addr` in the builtin-actors `runtime/src/builtin/shared.rs`. And then this API is ok. (Defer this for a follow-up)

_Originally posted by @anorth in https://github.com/helix-onchain/filecoin/pull/28#discussion_r928323583_

**Comment by alexytsu** [comment]
Pubkey addresses should probably just create the actor

Non-pubkey addresses TBD

**Comment by alexytsu** [comment]
https://github.com/helix-onchain/filecoin/pull/46 addresses this with three new helpers in the `token` module

`resolve_to_id` is used when an address needs to resolve to an ID and should be created if it doesn't already exist (e.g. receiving tokens, getting allowance)

`get_id` is used when an address needs to resolve to an ID but doesn't need to be created if it can be avoided (e.g. querying the balance of an address without an ID can return 0 without creating the address)

`expect_id` is used to resolve an `Address` to an `ActorID` when we know the Address must be an id-address (e.g. the caller of a method on the actor)

**Comment by anorth** [comment]
As discussed in Slack, we concluded that we should probably never return "Address uninitalised" errors to the caller, at least in relation to the owner or operator address. Instead error with insufficient balance or allowance, or succeed when the request was for zero value.
