### ISSUE TITLE
Decide policy for non-existent addresses

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#32]

**Comment by anorth** [comment]
This is #31 for public key addresses. Still TBD for other addresses, but let's make it really clear in the code where we can change this behaviour.

**Comment by alexytsu** [comment]
Continuing off the three functions described here, https://github.com/helix-onchain/filecoin/issues/31#issuecomment-1204597705 all addresses are handled via these helpers which implicitly gives us the behaviour
- BLS and SECP addresses have accounts initialised for them when data needs to be associated with them (i.e. storing an allowance or balance)
- Actor addresses will throw an error if an account is attempted to be initialised for them
- Any address, including Actor addresses will NOT throw an error for 'read-only' operations but instead return zero values (uninitialised accounts have no balance, no allowance etc.)
