### ISSUE TITLE
Get compiling integration tests working

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#7]
We would like to write example actors that consume the `fil_token` package and test the behaviour at the actor level

Currently actors within the [ref-fvm](https://github.com/filecoin-project/ref-fvm) repo are tested via the internal `fvm_integration_tests` package. However, attempting to use that here causes compilation errors.

**Comment by abright** [comment]
Integration tests using `fvm_integration_tests` are working in `main` now that https://github.com/helix-onchain/filecoin/pull/52 has merged
