### ISSUE TITLE
Update FRC-0042 rejection sampling to exclude 256 values

### ISSUE THREAD

**Issue by anorth** [helix-onchain/filecoin#74]
Implement the change described in https://github.com/filecoin-project/FIPs/pull/434

**Comment by abright** [comment]
Already done, and easy to extend if that excluded range gets extended further: https://github.com/helix-onchain/filecoin/pull/73/commits/cb3530c8017e6820dd398f315185927b1bad741a

**Comment by anorth** [comment]
Thanks, please close when that merges.

**Comment by abright** [comment]
merged...and published https://crates.io/crates/frc42_dispatch
