### ISSUE TITLE
More tests on example token actor

### ISSUE THREAD

**Issue by abright** [helix-onchain/filecoin#80]
Currently it only has a single integration test that mints tokens, this should be extended (or new tests added) to involve allowances, transfers and burn so all the major operations are covered. Need to be careful because those tests are quite heavy and could lead to even longer CI runs.

**Comment by anorth** [comment]
Some scenarios to integration-test:
- Mint to A who rejects hook
- Mint to token itself (rejected)

- A transfers to token itself (should be rejected)
- A transfers to A (zero, non-zero)
- A transfers to A and rejects hook
- A transfers to B (zero, non-zero, accept, reject)

- Mint to A, hook burns the tokens
- Mint to A, hook transfers to B
- Mint to A, hook transfers to B who rejects (but A keeps the tokens)

- A transfer to B, hook transfer to C
- A transfer to B, hook transfer to C, hook burns
- A transfer to B, hook transfer to C (rejected), B hook then transfers to D
- A transfer to B, hook transfer back to A (accept / reject)

- A transfer to B, hook burns but then aborts (tokens don't move)
- A transfer to B, hook transfer to C, but then B hook aborts (no move)

Assert all the expected token balances and token supply after each of these.

**Comment by anorth** [comment]
@abright could you update this issue with which, if any, remain as further tests we could write?

**Comment by abright** [comment]
Current state:
- [x] Mint to A who rejects hook
- [x] Mint to token itself (rejected)
- [x] A transfers to token itself (should be rejected)
- [x] A transfers to A (zero, non-zero)
- [ ] A transfers to A and rejects hook
- [x] A transfers to B (zero, non-zero, accept, reject)
- [x] Mint to A, hook burns the tokens
- [x] Mint to A, hook transfers to B
- [x] Mint to A, hook transfers to B who rejects (but A keeps the tokens)
- [x] A transfer to B, hook transfer to C
- [x] A transfer to B, hook transfer to C, hook burns
- [ ] A transfer to B, hook transfer to C (rejected), B hook then transfers to D
- [ ] A transfer to B, hook transfer back to A (accept / reject)
- [ ] A transfer to B, hook burns but then aborts (tokens don't move)
- [ ] A transfer to B, hook transfer to C, but then B hook aborts (no move)

Wasn't too hard to add the missing ones so I've done them in #193

**Comment by abright** [comment]
PR #193 is merged now which covers all the tests outlined here.
