### ISSUE TITLE
Get exit codes from TokenError without consuming it

### ISSUE THREAD

**Issue by anorth** [helix-onchain/filecoin#83]
The existing `impl From<TokenError> for ExitCode` consumes the error value. This makes it slightly annoying difficult to both get an exit code and invoke `to_string()` or do any other inspection of the error value.

The built-in actors use two statements to first inspect the message, then get the exit code at the last moment:
```
    fn actor_result(self) -> Result<T, ActorError> {
        self.map_err(|e| {
            let msg = e.to_string();
            ActorError::unchecked(ExitCode::from(e), msg)
        })
    }
```

It would be nice to find a way to get a code from a reference.

**Comment by alexytsu** [comment]
Completed via #87
