### ISSUE TITLE
Investigate gas-optimisations in fungible token library

### ISSUE THREAD

**Issue by alexytsu** [helix-onchain/filecoin#92]
Currently when balances and allowances are updated, the entire map is read from the blockstore and then written back. 

It may be more efficient to shard the balance map by ActorID so that the number of bytes written and read to/from the blockstore is lower. If sharding factor should be configurable if indeed it is overall more gas efficient.

If any map is changed, it will still be necessary to recompute the root Cid.

**Comment by anorth** [comment]
I think you might be misunderstanding the H/AMT, which already does what you describe. You might not be able to observe it with only a few keys in the map, but when there are many, it's essentially sharded. We can adjust the bitwidth parameter to optimise - optimal number depends on the byte size of each value (i.e. tokenamount).

**Comment by alexytsu** [comment]
Good to know - thanks!
